//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Pa:1:B1:21:0:B1
        ///2Pa:1:B2:22:0:B2
        ///3Pa:1:B3:23:0:B3
        ///4Pa:1:B4:24:0:B4
        ///5Pa:1:B5:25:0:B5
        ///6Pa:1:B6:26:0:B6
        ///7Pa:1:B7:27:0:B7
        ///8Pa:1:B8:28:0:B8
        ///1Ro:A:A1:11:0:A1
        ///1Kn:A:A2:12:0:A2
        ///1Bi:A:A3:13:0:A3
        ///Kin:A:A4:14:0:A4
        ///Que:A:A5:15:0:A5
        ///2Bi:A:A6:16:0:A6
        ///2Kn:A:A7:17:0:A7
        ///2Ro:A:A8:18:0:A8
        ///1Pa:1:G1:71:0:G1
        ///2Pa:1:G2:72:0:G2
        ///3Pa:1:G3:73:0:G3
        ///4Pa:1:G4:74:0:G4
        ///5Pa:1:G5:75:0:G5
        ///6Pa:1:G6:76:0:G6
        ///7Pa:1:G7:77:0:G7
        ///8Pa:1:G8:78:0:G8
        ///1Ro:A:H1:81:0:H1
        ///1Kn:A:H2:82:0:H2
        ///1Bi:A:H3:83:0:H3
        ///Kin:A:H4:84:0:H4
        ///Que:A:H5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Black_Origin {
            get {
                return ResourceManager.GetString("Black_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess {
            get {
                object obj = ResourceManager.GetObject("chess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_bishop_black_large {
            get {
                object obj = ResourceManager.GetObject("chess_bishop_black_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_bishop_black_small {
            get {
                object obj = ResourceManager.GetObject("chess_bishop_black_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_bishop_white_large {
            get {
                object obj = ResourceManager.GetObject("chess_bishop_white_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_bishop_white_small {
            get {
                object obj = ResourceManager.GetObject("chess_bishop_white_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Chess_Draw_Sound {
            get {
                return ResourceManager.GetStream("Chess_Draw_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_king_black_large {
            get {
                object obj = ResourceManager.GetObject("chess_king_black_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_king_black_small {
            get {
                object obj = ResourceManager.GetObject("chess_king_black_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_king_white_large {
            get {
                object obj = ResourceManager.GetObject("chess_king_white_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_king_white_small {
            get {
                object obj = ResourceManager.GetObject("chess_king_white_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_knight_black_large {
            get {
                object obj = ResourceManager.GetObject("chess_knight_black_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_knight_black_small {
            get {
                object obj = ResourceManager.GetObject("chess_knight_black_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_knight_white_large {
            get {
                object obj = ResourceManager.GetObject("chess_knight_white_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_knight_white_small {
            get {
                object obj = ResourceManager.GetObject("chess_knight_white_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Chess_Lose_Sound {
            get {
                return ResourceManager.GetStream("Chess_Lose_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_pawn_black_large {
            get {
                object obj = ResourceManager.GetObject("chess_pawn_black_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_pawn_black_small {
            get {
                object obj = ResourceManager.GetObject("chess_pawn_black_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_pawn_white_large {
            get {
                object obj = ResourceManager.GetObject("chess_pawn_white_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_pawn_white_small {
            get {
                object obj = ResourceManager.GetObject("chess_pawn_white_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Chess_Piece_Move {
            get {
                return ResourceManager.GetStream("Chess_Piece_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_queen_black_large {
            get {
                object obj = ResourceManager.GetObject("chess_queen_black_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_queen_black_small {
            get {
                object obj = ResourceManager.GetObject("chess_queen_black_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_queen_white_large {
            get {
                object obj = ResourceManager.GetObject("chess_queen_white_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_queen_white_small {
            get {
                object obj = ResourceManager.GetObject("chess_queen_white_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_rook_black_large {
            get {
                object obj = ResourceManager.GetObject("chess_rook_black_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_rook_black_small {
            get {
                object obj = ResourceManager.GetObject("chess_rook_black_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_rook_white_large {
            get {
                object obj = ResourceManager.GetObject("chess_rook_white_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chess_rook_white_small {
            get {
                object obj = ResourceManager.GetObject("chess_rook_white_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Chess_Win_Sound {
            get {
                return ResourceManager.GetStream("Chess_Win_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chessHelp {
            get {
                object obj = ResourceManager.GetObject("chessHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap helpIcon {
            get {
                object obj = ResourceManager.GetObject("helpIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa:1: x+1&amp;&amp;y || x+2&amp;&amp;y || spc(x+1&amp;&amp;y+1):x+1&amp;&amp;y+1 || spc(x-1&amp;&amp;y+1):x-1&amp;&amp;y+1;
        ///Pa:A: x+1&amp;&amp;y || spc(x+1&amp;&amp;y+1):x+1&amp;&amp;y+1 || spc(x-1&amp;&amp;y+1):x-1&amp;&amp;y+1;
        ///Ro:A: x+n&amp;&amp;y || x&amp;&amp;y+m;
        ///Kn:A: x+3&amp;&amp;y+1 || x+1&amp;&amp;y+3 || x-1&amp;&amp;y+3 || x-3&amp;&amp;y+1 || x-3&amp;&amp;y-1 || x-1&amp;&amp;y-3 || x+1&amp;&amp;y-3 || x+3&amp;&amp;y-1;
        ///Bi:A: n==m;
        ///Qu:A: n==m || x+n&amp;&amp;y || x&amp;&amp;y+m;
        ///Ki:A: x&amp;&amp;y+1 || x+1&amp;&amp;y+1 || x+1&amp;&amp;y || x+1&amp;&amp;y-1 || x&amp;&amp;y-1 || x-1&amp;&amp;y-1 || x-1&amp;&amp;y || x-1&amp;&amp;y+1;.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Pa:1:B1:21:0:B1
        ///2Pa:1:B2:22:0:B2
        ///3Pa:1:B3:23:0:B3
        ///4Pa:1:B4:24:0:B4
        ///5Pa:1:B5:25:0:B5
        ///6Pa:1:B6:26:0:B6
        ///7Pa:1:B7:27:0:B7
        ///8Pa:1:B8:28:0:B8
        ///1Ro:A:A1:11:0:A1
        ///1Kn:A:A2:12:0:A2
        ///1Bi:A:A3:13:0:A3
        ///Que:A:A4:14:0:A4
        ///Kin:A:A5:15:0:A5
        ///2Bi:A:A6:16:0:A6
        ///2Kn:A:A7:17:0:A7
        ///2Ro:A:A8:18:0:A8
        ///1Pa:1:G1:71:0:G1
        ///2Pa:1:G2:72:0:G2
        ///3Pa:1:G3:73:0:G3
        ///4Pa:1:G4:74:0:G4
        ///5Pa:1:G5:75:0:G5
        ///6Pa:1:G6:76:0:G6
        ///7Pa:1:G7:77:0:G7
        ///8Pa:A:G8:78:0:G8
        ///1Ro:A:H1:81:0:H1
        ///1Kn:A:H2:82:0:H2
        ///1Bi:A:H3:83:0:H3
        ///Que:A:H4:84:0:H4
        ///Kin:A:H5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string White_Origin {
            get {
                return ResourceManager.GetString("White_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wood_grain_effect_clipart {
            get {
                object obj = ResourceManager.GetObject("wood-grain-effect-clipart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
